version: '3'
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file: 
      - database.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    volumes:
      - ./redis-data/:/var/lib/redis/data